# Generated by Django 3.2.5 on 2021-07-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='tags',
            field=models.ManyToManyField(to='mainApp.Tag'),
        ),
    ]
