# Generated by Django 3.2.5 on 2021-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210711_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='is_publish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
